name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar xvzf ngrok-v3-stable-linux-amd64.tgz
    
    - name: Auth ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    
    - name: Setup SSH
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server
        sudo systemctl start ssh
        sudo systemctl enable ssh
    
    - name: Set User Password
      run: |
        echo "runner:P@ssw0rd!" | sudo chpasswd
    
    - name: Start ngrok
      run: |
        ./ngrok tcp 22 > ngrok.log 2>&1 &
        sleep 10
        cat ngrok.log
        echo "=========================================="
        echo "Username: runner"
        echo "Password: P@ssw0rd!"
        echo "=========================================="
        tail -f ngrok.log
